manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk-adaptive-key
      url-base: https://github.com/urob/zmk-adaptive-key
    - name: zmk-auto-layer
      url-base: https://github.com/urob/zmk-auto-layer
    - name: zmk-helpers
      url-base: https://github.com/urob/zmk-helpers
    - name: zmk-leader-key
      url-base: https://github.com/urob/zmk-leader-key
    - name: zmk-tri-state
      url-base: https://github.com/dhruvinsh/zmk-tri-state
    - name: zmk-unicode
      url-base: https://github.com/urob/zmk-unicode
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
