#!/usr/bin/env python3
"""Regenerate boards/shields/cosmos/cosmos-layouts.dtsi (ZMK Studio picture).

Units: centi-keyunits (100 = one key). Left half spans x 0..600, the right
half is its mirror at x 800..1400. Purely cosmetic - only the key ORDER
matters and it must match default_transform's map in cosmos.dtsi.

    python3 scripts/gen_cosmos_layout.py > boards/shields/cosmos/cosmos-layouts.dtsi
"""
stagger = [60, 60, 20, 0, 20, 40]          # column drop, outer -> inner
mirror = lambda x: 1300 - x
keys = []
for r in range(4):                          # finger rows 0-3
    left = [(c * 100, stagger[c] + r * 100) for c in range(6)]
    right = [(mirror(x), y) for (x, y) in reversed(left)]
    keys += left + right
# row 4: three thumb keys per half (matrix cols 3-5), outer -> inner
left = [(300 + i * 100, 540) for i in range(3)]
right = [(mirror(x), y) for (x, y) in reversed(left)]
keys += left + right
assert len(keys) == 54

print("""/*
 * Physical layout for ZMK Studio. GENERATED by scripts/gen_cosmos_layout.py -
 * purely cosmetic, but the key ORDER must match default_transform's map in
 * cosmos.dtsi.
 * SPDX-License-Identifier: MIT
 */

#include <physical_layouts.dtsi>

/ {
    cosmos_layout: cosmos_layout {
        compatible = "zmk,physical-layout";
        display-name = "Cosmos 5x6";
        keys  //                     w   h    x    y  rot  rx  ry""")
for i, (x, y) in enumerate(keys):
    sep = "=" if i == 0 else ","
    end = ";" if i == len(keys) - 1 else ""
    print(f"            {sep} <&key_physical_attrs 100 100 {x:4d} {y:4d}    0   0   0>{end}")
print("""    };
};""")
